name: byte

channels:
  - conda-forge
dependencies:
  - pip
  - cython
  - 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
  - cython_bbox
  - pip:
    - -r requirements.txt
  
